config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  resources :shares
  
  get './shares', to: 'shares#index'
  resources :playlists, only: [:create, :index, :show, :destroy]
  resources :shares, only: [:create]

  post '/users/:user_id/search', to: 'search_histories#search'
  get '/users/:user_id/recommendations', to: 'recommendations#recommend'
  post '/playlists/:playlist_id/musics/:music_id', to: 'playlists#add_music_to_playlist'
  get '/playlists/:playlist_id/musics/:music_id', to: 'playlists#add_music_to_playlist'
  get '/playlists/:playlist_id/musics/', to: 'playlists#fetch_added_songs'



  resources :users
  resources :music, only: [:index, :show, :create]
  resources :artists
  get '/users/:id', to: 'users#show'
  post 'signup', to: 'users#create'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/me/:id', to: 'sessions#show'
  get '/musics', to: 'music#index'
  post '/musics', to: 'music#create'
  get '/artist', to: 'artist#index'
  post '/artist', to: 'artist#create'
  post '/shares', to: 'shares#create'
  delete '/playlists/:id', to: 'playlists#destroy'
  get '/musics/:id', to: 'music#show'



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/share.rb
class Share < ApplicationRecord
  validates :user_id, presence: true
  validates :platform, presence: true
  validates :share_url, presence: true

  
  belongs_to :user
  belongs_to :song

  validates :song_id, presence: true
end

app/controllers/api/v1/share_controller.rb
class Api::V1::ShareController < ApplicationController
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  before_action :set_share, only: [:show, :update, :destroy]

  
  def index
    shares = Share.all
    render json: shares
  end


  end

  
  def create
    share = Share.new(share_params)

    if share.save
      render json: share, status: :created
    else
      render json: { errors: share.errors }, status: :unprocessable_entity
    end
  end

  
  def update
    if @share.update(share_params)
      render json: @share
    else
      render json: { errors: @share.errors }, status: :unprocessable_entity
    end
  end


  def destroy
    @share.destroy
    head :no_content
  end

  private

  def set_share
    @share = Share.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render json: { error: 'Share not found' }, status: :not_found
  end

  def share_params
    params.require(:share).permit(:user_id, :platform, :share_url, :song_id)
  end
end

app/helpers/api/v1/share_helper.rb
module Api::V1::ShareHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/views/shares/_form.html.erb
<%= form_with(model: share) do |form| %>
  <% if share.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(share.errors.count, "error") %> prohibited this share from being saved:</h2>

      <ul>
        <% share.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :platform, style: "display: block" %>
    <%= form.text_field :platform %>
  </div>

  <div>
    <%= form.label :share_url, style: "display: block" %>
    <%= form.text_field :share_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shares/_share.html.erb
<div id="<%= dom_id share %>">
  <p>
    <strong>User:</strong>
    <%= share.user_id %>
  </p>

  <p>
    <strong>Platform:</strong>
    <%= share.platform %>
  </p>

  <p>
    <strong>Share url:</strong>
    <%= share.share_url %>
  </p>

</div>

app/views/shares/edit.html.erb
<h1>Editing share</h1>

<%= render "form", share: @share %>

<br>

<div>
  <%= link_to "Show this share", @share %> |
  <%= link_to "Back to shares", shares_path %>
</div>

app/views/shares/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Shares</h1>

<div id="shares">
  <% @shares.each do |share| %>
    <%= render share %>
    <p>
      <%= link_to "Show this share", share %>
    </p>
  <% end %>
</div>

<%= link_to "New share", new_share_path %>

app/views/shares/new.html.erb
<h1>New share</h1>

<%= render "form", share: @share %>

<br>

<div>
  <%= link_to "Back to shares", shares_path %>
</div>

app/views/shares/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @share %>

<div>
  <%= link_to "Edit this share", edit_share_path(@share) %> |
  <%= link_to "Back to shares", shares_path %>

  <%= button_to "Destroy this share", @share, method: :delete %>
</div>